stages:
  - publish
  - test

.publish-applet:
  stage: publish
  image: node:16-alpine
  before_script:
    - npm i @signageos/cli -g
  script:
    - cd $APPLET_PATH
    - npm install
    - npm run upload-applet-ci

.test-applet-device:
  stage: test
  image: node:16-alpine
  when: manual
  script:
    - cd $APPLET_PATH
    - npm install
    - npm test

# Sample Applet
publish-applet:sample:
  extends: .publish-applet
  variables:
    APPLET_PATH: .
    SOS_APPLET_UID: ca2123037c0ceeaceab255707ff94924ecc2830aaaa3cee88c

test-applet-device:sample:tizen-2.4:
  extends: .test-applet-device
  variables:
    APPLET_PATH: .
    SOS_APPLET_VERSION: 2.0.0
    SOS_APPLET_UID: ca2123037c0ceeaceab255707ff94924ecc2830aaaa3cee88c
    SOS_DEVICE_UID: e824fcd24a4f8bdf962974e45c1a9901606b50771520a0a907625
